### ISSUE TITLE
/camera_info topic?  Using Two Monocular cameras for Stereo?

### ISSUE THREAD

**Issue by javadan** [NVIDIA-ISAAC-ROS/isaac_ros_argus_camera#7]
Hi there

Is the stereo vision only for realsense cameras?

Is there a way to do it with two monocular cameras, with clever remapping?

I currently get stuck because of /camera_info requirements in most of the ISAAC ROS packages.  

I've tried dropping a left.yaml and right.yaml (files from the ROS calibration process) under the .ros directory, but the `camera_info_url` doesn't seem to work.

` what():  found unknown ROS arguments: 'camera_info_url=file:///home/admin/.ros/camera_info/left.yaml'`

Without calibration, It starts up warning:
`[WARN] [1650544642.816017010] [argus_monocular]: Cannot get ISyncSensorCalibrationData interface`

And /camera_info is all zeroes

```
admin@chicken:/workspaces/isaac_ros-dev/src/isaac_ros_argus_camera$ ros2 topic echo /camera_info
header:
  stamp:
    sec: 1650544846
    nanosec: 49888246
  frame_id: '6073'
height: 0
width: 0
distortion_model: ''
d: []
k: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
r: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
p: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
```

So something straightforward like the `isaac_ros_image_pipeline` won't do anything, if I try check the topics.

`[ERROR] [1650545104.173691674] [rectify_color]: Rectified topic '/image_rect' requested but camera publishing '/camera_info' is uncalibrated`

I'm not sure how to publish the camera info so that the `/camera_info` topic is usable by the rest of the ISAAC ROS suite.  (Or likewise /left/camera_info and /right/camera_info, or whatever, for stereo).

If stereo is possible by remapping a left and a right camera to the input topics required by say, the stereo camera, or the stereo_proc, how would I do that?

Can I remap the output topics on the command line?  Or should I be making a launch file to handle the remappings?

Thanks
